// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG9sErkUAZOeSJlxx1tGbTuJLCyzr9CT8',
    appId: '1:393687814607:web:f94473f937fa8612b302ba',
    messagingSenderId: '393687814607',
    projectId: 'bus-gps-tracker-6e8f9',
    authDomain: 'bus-gps-tracker-6e8f9.firebaseapp.com',
    storageBucket: 'bus-gps-tracker-6e8f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ1XHK6y973IxF-9ThBJajW-bhguGbNgo',
    appId: '1:393687814607:android:241ffe103c0bf8aab302ba',
    messagingSenderId: '393687814607',
    projectId: 'bus-gps-tracker-6e8f9',
    storageBucket: 'bus-gps-tracker-6e8f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp62Ea0GMgt50kWhIUbZmHRzXTvKreCt8',
    appId: '1:393687814607:ios:7ed10f9bc85d07afb302ba',
    messagingSenderId: '393687814607',
    projectId: 'bus-gps-tracker-6e8f9',
    storageBucket: 'bus-gps-tracker-6e8f9.firebasestorage.app',
    iosBundleId: 'com.example.busGpsSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp62Ea0GMgt50kWhIUbZmHRzXTvKreCt8',
    appId: '1:393687814607:ios:7ed10f9bc85d07afb302ba',
    messagingSenderId: '393687814607',
    projectId: 'bus-gps-tracker-6e8f9',
    storageBucket: 'bus-gps-tracker-6e8f9.firebasestorage.app',
    iosBundleId: 'com.example.busGpsSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG9sErkUAZOeSJlxx1tGbTuJLCyzr9CT8',
    appId: '1:393687814607:web:c6d66c7bf1a61144b302ba',
    messagingSenderId: '393687814607',
    projectId: 'bus-gps-tracker-6e8f9',
    authDomain: 'bus-gps-tracker-6e8f9.firebaseapp.com',
    storageBucket: 'bus-gps-tracker-6e8f9.firebasestorage.app',
  );
}
